name: rsync_deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Output secrets
      run: |
        echo "DEPLOY_REMOTE_PATH: ${{ secrets.DEPLOY_REMOTE_PATH }}"
        echo "DEPLOY_REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}"
        echo "DEPLOY_REMOTE_PORT: ${{ secrets.DEPLOY_REMOTE_PORT }}"
        echo "DEPLOY_REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}"
        echo "DEPLOY_REMOTE_KEY: ${{ secrets.DEPLOY_REMOTE_KEY }}"


    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzrO --no-perms
        path: .
        remote_path: ${{ secrets.DEPLOY_REMOTE_PATH_NAME }}
        remote_host: ${{ secrets.DEPLOY_REMOTE_HOST_NAME }}
        remote_port: ${{ secrets.DEPLOY_REMOTE_PORT_NAME }}
        remote_user: ${{ secrets.DEPLOY_REMOTE_USER_NAME }}
        remote_key: ${{ secrets.DEPLOY_REMOTE_KEY_NAME }}
